version: '3.8'

services:
  mysql:
    image: mysql
    container_name: my_movies_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysqlData:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'